### ISSUE TITLE
Confirm status of "improving OBS departure time" suggestions

### ISSUE THREAD

**Issue by e-lo** [sfcta/fast-trips-validation#3]
Is this process incorporated yet? 

If so, please add this to the documentation.  

If not, please save to a wiki page in this github repo and link to it from a read me and create issues to incorporate it.

https://docs.google.com/document/d/1LgIb8SaWVFWUpIa_bHYqKPfvWbuQN1y6-criZA6EBIs/edit

**Comment by bhargavasana** [comment]
This is still a TODO. I have added another issue with link to wiki page describing the suggested enhancements.
